apiVersion: v1
kind: Template
message: |-
  The following service(s) have been created in your project: Tekton (...) resources.
metadata:
  name: cicd-tekton
  annotations:
    openshift.io/display-name: Tekton
    openshift.io/provider-display-name: Tereza Gabrielova
    tags: tekton,cicd
    template.openshift.io/bindable: "false"
labels:
  template: tekton
  app: tekton
objects:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: build-and-deploy
  spec:
    workspaces: 
    - name: shared-workspace
    resources:
    - name: app-git
      type: git
    - name: app-image
      type: image
    params: 
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "release-tech-preview-3"
    - name: IMAGE
      type: string
      description: image to be build from the code
    tasks:
    - name: build
      params:
      - name: TLSVERIFY
        value: "false"
      resources:
        inputs:
        - name: source
          resource: app-git
        outputs:
        - name: image
          resource: app-image
      taskRef:
        name: s2i-php
    - name: deploy
      params:
      - name: ARGS
        value: start-build ${NAME}
      runAfter:
        - build
      taskRef:
        name: openshift-client
- apiVersion: tekton.dev/v1beta1
  kind: Task
  metadata:
    name: openshift-client
    labels:
      app.kubernetes.io/version: "0.1"
    annotations:
      tekton.dev/pipelines.minVersion: "0.11.3"
      tekton.dev/tags: openshift-client, cli
      tekton.dev/displayName: "openshift client"
  spec:
    description: >-
      openshift-client task helps to run oc commands.
    params:
      - default: help
        description: The OpenShift CLI arguments to run
        name: ARGS
    steps:
    - name: oc
      args: ['$(params.ARGS)']
      command: ['/usr/local/bin/oc']
      image: quay.io/openshift-pipeline/openshift-cli:latest
- apiVersion: tekton.dev/v1beta1
  kind: Task
  metadata:
    name: s2i-php
    labels:
      app.kubernetes.io/version: "0.1"
    annotations:
      tekton.dev/pipelines.minVersion: "0.11.3"
      tekton.dev/tags: s2i, php
      tekton.dev/displayName: "s2i php"
  spec:
    description: >-
      s2i-php task fetches a Git repository and builds and
      pushes a container image using S2I and a PHP builder image.
    params:
      - name: MINOR_VERSION
        description: The minor version of the php
        default: '2'
        type: string
      - name: PATH_CONTEXT
        description: The location of the path to run s2i from.
        default: .
        type: string
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
        type: string
    resources:
      inputs:
        - name: source
          type: git
      outputs:
        - name: image
          type: image
    steps:
    - name: generate
      image: quay.io/openshift-pipeline/s2i:latest
      workingDir: /workspace/source
      command: ['s2i', 'build', '$(params.PATH_CONTEXT)', 'tgabriel/openshift-nginx-phpfpm-s2i:1.0', '--as-dockerfile', '/gen-source/Dockerfile.gen']
      volumeMounts:
      - mountPath: /gen-source
        name: gen-source
    - name: build
      image: quay.io/buildah/stable:v1.11.0
      workingdir: /gen-source
      command: ['buildah', 'bud', '--tls-verify=$(params.TLSVERIFY)', '--layers', '-f', '/gen-source/Dockerfile.gen', '-t', '$(resources.outputs.image.url)', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
      securityContext:
        privileged: true
    - name: php-testing
      workingDir: /workspace/source
      command: ['phpunit', '--bootstrap', '/workspace/source/src/autoload.php', '/workspace/source/tests/EmailTest.php']
      image: jakzal/phpqa:latest
      volumeMounts:
      - mountPath: /gen-source
        name: gen-source
    - name: push
      image: quay.io/buildah/stable:v1.11.0
      command: ['buildah', 'push', '--tls-verify=$(params.TLSVERIFY)', '$(resources.outputs.image.url)', 'docker://$(resources.outputs.image.url)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    volumes:
    - emptyDir: {}
      name: varlibcontainers
    - emptyDir: {}
      name: gen-source
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: app-git
  spec:
    params:
    - name: url
      value: https://github.com/Tessg22/making-a-wordpress-developer-stack-on-openshift-4
    type: git
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: app-image
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/openshift-nginx-phpfpm-s2i
    type: image
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: openshift-nginx-phpfpm-deploy-pipelinerun-
  spec:
    pipelineRef:
      name: build-and-deploy
    params:
    - name: deployment-name
      value: openshift-nginx-phpfpm
    - name: git-url
      value: https://github.com/Tessg22/making-a-wordpress-developer-stack-on-openshift-4.git
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-ui
    workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    resources:
    - name: app-git
      resourceRef:
        name: app-git
    - name: app-image
      resourceRef:
        name: app-image    
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerTemplate
  metadata:
    name: openshift-nginx-phpfpm
  spec:
    params:
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: build-deploy-$(tt.params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-and-deploy
        params:
        - name: deployment-name
          value: $(tt.params.git-repo-name)
        - name: git-url
          value: $(tt.params.git-repo-url)
        - name: git-revision
          value: $(tt.params.git-revision)
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/$(tt.params.git-repo-name)
        workspaces:
        - name: shared-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 500Mi
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerBinding
  metadata:
    name: openshift-nginx-phpfpm
  spec:
    params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.head_commit.id)
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: Trigger
  metadata:
    name: openshift-nginx-phpfpm
  spec:
    serviceAccountName: pipeline
    bindings:
      - ref: openshift-nginx-phpfpm
    template:
      name: openshift-nginx-phpfpm
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: EventListener
  metadata:
    name: openshift-nginx-phpfpm
  spec:
    serviceAccountName: pipeline
    triggers:
    - triggerRef: openshift-nginx-phpfpm
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  from: 'wordpress-[a-f0-9]{6}'
  generate: expression
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
